name: CI

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build Godot
      uses: josephbmanley/build-godot-action@v1.3.1
      with:
        # Name of the exported binary
        name: Steam_VR_Demo.exe
        # Name of the preset in `export_presets.cfg` to use
        preset: "Windows_Desktop"
        # Optional name of the subdirectory to put exported project in
        subdirectory: build
        # Set true to output an artifact zip file
        package: true
